# Global settings
source global-config.conf
source family-rk3506.conf

# Board-specific
BOARD=luckfox-lyra-zero-w
ENABLE_EXTENSIONS="$ENABLE_EXTENSIONS,unblock-rfkill,armbian-web-config"

# Disable UART interrupts during boot
# preventing UART-enabled hats from interfering with uboot.
function post_family_config__override_bootdelay() {
	declare -g BOOTDELAY="-2"
}
