# Global settings
# See https://docs.armbian.com/Developer-Guide_Build-Switches/

# Whitelabeling
VENDOR="mPWRD-OS"
VENDORURL="https://github.com/mPWRD-OS/mPWRD-OS/"
VENDORSUPPORT="https://discord.gg/meshtastic"
VENDORPRIVACY="https://meshtastic.org/docs/legal/privacy/"
VENDORBUGS="https://github.com/mPWRD-OS/mPWRD-OS/issues"
VENDORDOCS="https://github.com/mPWRD-OS/mPWRD-OS/wiki"
# VENDORLOGO="armbian-logo"
# VENDORCOLOR="247;16;0"

# Release settings
RELEASE=trixie
DOCKER_ARMBIAN_BASE_IMAGE="ubuntu:noble"
INSTALL_HEADERS=yes
INSTALL_ARMBIAN_FIRMWARE=yes
BUILD_DESKTOP=no
BUILD_MINIMAL=yes
DEB_COMPRESS=xz
# NetworkManager / nmcli is more user-friendly.
NETWORKING_STACK="network-manager"
EXTRAWIFI=yes
COMPRESS_OUTPUTIMAGE="xz,sha"
ENABLE_EXTENSIONS="mpwrd-os-pkgs,mpwrd-misc-pkgs,meshtasticd"
MESHTASTICD_CHANNEL="beta"
